// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJuYKbncilEFphNSA7wSf4r2nLEv0eyYA',
    appId: '1:804632439345:web:7ffaa5f969d2244a334310',
    messagingSenderId: '804632439345',
    projectId: 'aouk-2178e',
    authDomain: 'aouk-2178e.firebaseapp.com',
    storageBucket: 'aouk-2178e.firebasestorage.app',
    measurementId: 'G-PGH43J0TXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3-rQXy6cYoz7UYo38TErcp-p0Az5hLOM',
    appId: '1:804632439345:android:ad23fbf6bb5f72db334310',
    messagingSenderId: '804632439345',
    projectId: 'aouk-2178e',
    storageBucket: 'aouk-2178e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkHocMBnEkcktSMzADRmGGJnq2es8gHHA',
    appId: '1:804632439345:ios:4e055100d6db832b334310',
    messagingSenderId: '804632439345',
    projectId: 'aouk-2178e',
    storageBucket: 'aouk-2178e.firebasestorage.app',
    iosBundleId: 'com.example.noScreenshot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkHocMBnEkcktSMzADRmGGJnq2es8gHHA',
    appId: '1:804632439345:ios:4e055100d6db832b334310',
    messagingSenderId: '804632439345',
    projectId: 'aouk-2178e',
    storageBucket: 'aouk-2178e.firebasestorage.app',
    iosBundleId: 'com.example.noScreenshot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJuYKbncilEFphNSA7wSf4r2nLEv0eyYA',
    appId: '1:804632439345:web:95280d965a7ba72c334310',
    messagingSenderId: '804632439345',
    projectId: 'aouk-2178e',
    authDomain: 'aouk-2178e.firebaseapp.com',
    storageBucket: 'aouk-2178e.firebasestorage.app',
    measurementId: 'G-RW0YS3JDRR',
  );
}
